- alias: "Entry door opened"
  id: automation.entry_door_opened
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.0x00158d0007ed2829_contact
      to: "on"      
  action:
    - alias: "Light on"
      service: light.turn_on
      target:
        entity_id: light.loznice_petr

- alias: "Entry door closed"
  id: automation.entry_door_closed
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.0x00158d0007ed2829_contact
      to: "off"      
  action:
    - alias: "Light on"
      service: light.turn_off
      target:
        entity_id: light.loznice_petr